
apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-cloud-room
  labels:
    app: www-cloud-room
  namespace: peiyou-review
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: www-cloud-room
  template:
    metadata:
      labels:
        app: www-cloud-room
    spec:
      containers:
        - name: www-cloud-room
          image: registry-vpc.cn-shanghai.aliyuncs.com/lkl-review/www-cloud-room:0.1
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
      dnsPolicy: ClusterFirst
